title: Taguette Workshop
remote_theme: pmarsceill/just-the-docs

# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

aux_links:
  "UVic Libraries Digital Scholarship Commons":
    - "//uvic.ca/librar/dsc"

aux_links_new_tab: true

# Footer Information

footer_content: "<img src=\"https://i.creativecommons.org/l/by/4.0/88x31.png\" style=\"float:right;\">
Copyright &copy; 2021 <a href=\"https://uvic.ca/library/dsc/\">UVic Libraries Digital Scholarship Commons</a> - <a href=\"mailto:dscommons@uvic.ca\">dscommons@uvic.ca</a>
Distributed by an <a href=\"http://creativecommons.org/licenses/by/4.0/\">Creative Commons Attribution 4.0 International License.</a>

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"

