title: "Taguette: Qualitative Coding & Analysis"
remote_theme: pmarsceill/just-the-docs

# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"
